---
mac_minis:
  hosts:
    mini-1:
      ansible_host: 192.168.x.x
      ansible_user: your_username
      ansible_python_interpreter: /opt/homebrew/bin/python3.10
    mini-2:
      ansible_host: 192.168.x.x
      ansible_user: your_username
      ansible_python_interpreter: /opt/homebrew/bin/python3.10
  vars:
    ansible_ssh_private_key_file: ~/.ssh/your_private_key
    projects_root: ~/projects
    repo_url: https://github.com/your_username/your_repo.git
