---
- name: Setup Mac Minis for distributed ML
  hosts: mac_minis
  gather_facts: yes
  tasks:
    - name: Install Homebrew
      shell: |
        if ! command -v brew &> /dev/null; then
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        fi
      args:
        creates: /opt/homebrew/bin/brew

    - name: Add Homebrew to PATH
      lineinfile:
        path: "{{ ansible_user_dir }}/.zprofile"
        line: 'eval "$(/opt/homebrew/bin/brew shellenv)"'
        create: yes

    - name: Install Python 3.10
      homebrew:
        name: python@3.10
        state: present

    - name: Create projects directory
      file:
        path: "{{ projects_root }}"
        state: directory

    - name: Clone project repository
      git:
        repo: "{{ repo_url }}"
        dest: "{{ projects_root }}/mac-mini-connect"

    - name: Create Python virtual environment
      pip:
        virtualenv: "{{ projects_root }}/mac-mini-connect/venv"
        virtualenv_command: python3.10 -m venv
        requirements: "{{ projects_root }}/mac-mini-connect/requirements.txt"
